# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-29 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.TextField(null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('token_type', models.CharField(default='Bearer', max_length=30)),
                ('expires_on', models.DateTimeField()),
            ],
        ),
    ]
