# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluidreview', '0002_webhookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookrequest',
            name='amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='award_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='award_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='award_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Failed', 'Failed'), ('Succeeded', 'Succeeded')], default='Created', max_length=10),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='submission_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='user_email',
            field=models.CharField(null=True, blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
