# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-27 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluidreview', '0003_webhookrequest_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookrequest',
            options={'ordering': ['award_id', 'created_on']},
        ),
    ]
