# Generated by Django 1.10.5 on 2017-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("profiles", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fluidreview_id",
            field=models.IntegerField(null=True, blank=True),
        )
    ]
