# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-13 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_fluidreview_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='smaplly_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
