# Generated by Django 1.10.5 on 2018-11-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("profiles", "0002_profile_fluidreview_id")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="smapply_id",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
