# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-13 18:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("profiles", "0003_profile_smapply_id")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="smapply_user_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
