# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-23 17:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("profiles", "0004_profile_smapply_user_data")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="smapply_demographic_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
