# Generated by Django 2.2.10 on 2020-04-22 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_profile_smapply_demographic_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_size',
            field=models.IntegerField(blank=True, choices=[(None, '----'), (1, 'Small/Start-up (1+ employees)'), (9, 'Small/Home office (1-9 employees)'), (99, 'Small (10-99 employees)'), (999, 'Small to medium-sized (100-999 employees)'), (9999, 'Medium-sized (1000-9999 employees)'), (10000, 'Large Enterprise (10,000+ employees)'), (0, "Other (N/A or Don't know)")], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other/Prefer Not to Say')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='highest_education',
            field=models.CharField(blank=True, choices=[(None, '----'), ('Doctorate', 'Doctorate'), ("Master's or professional degree", "Master's or professional degree"), ("Bachelor's degree", "Bachelor's degree"), ('Associate degree', 'Associate degree'), ('Secondary/high school', 'Secondary/high school'), ('Junior secondary/junior high/middle school', 'Junior secondary/junior high/middle school'), ('Elementary/primary school', 'Elementary/primary school'), ('No formal education', 'No formal education'), ('Other education', 'Other education')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_function',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='leadership_level',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_experience',
            field=models.IntegerField(blank=True, choices=[(None, '----'), (2, 'Less than 2 years'), (5, '2-5 years'), (10, '6 - 10 years'), (15, '11 - 15 years'), (20, '16 - 20 years'), (21, 'More than 20 years'), (0, 'Prefer not to say')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LegalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('street_address_1', models.CharField(blank=True, max_length=60)),
                ('street_address_2', models.CharField(blank=True, max_length=60)),
                ('street_address_3', models.CharField(blank=True, max_length=60)),
                ('street_address_4', models.CharField(blank=True, max_length=60)),
                ('street_address_5', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=2, validators=[profiles.models.validate_iso_3166_1_code])),
                ('state_or_territory', models.CharField(blank=True, max_length=6, validators=[profiles.models.validate_iso_3166_2_code])),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeEmailRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('new_email', models.EmailField(max_length=254)),
                ('code', models.CharField(default=profiles.models.generate_change_email_code, max_length=32, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('expires_on', models.DateTimeField(default=profiles.models.generate_change_email_expires)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_email_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('expires_on', 'confirmed', 'code')},
            },
        ),
    ]
