# Generated by Django 2.2.10 on 2020-04-30 14:33

from django.contrib.auth import get_user_model
from django.db import migrations


def populate_addresses(apps, schema_editor):
    """
    Populate LegalAddress for users who don't have it
    """
    User = get_user_model()
    LegalAddress = apps.get_model("profiles", "LegalAddress")

    for user in User.objects.filter(legal_address=None).iterator():
        LegalAddress.objects.get_or_create(user_id=user.id)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_timestamped'),
    ]

    operations = [
        migrations.RunPython(populate_addresses, migrations.RunPython.noop)
    ]
