# Generated by Django 3.2.12 on 2022-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_profile_can_skip_application_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="smapply_demographic_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="smapply_user_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
