# Generated by Django 2.2.10 on 2020-05-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("applications", "0002_minor_fixes")]

    operations = [
        migrations.RemoveField(model_name="quizsubmission", name="review_status"),
        migrations.RemoveField(model_name="quizsubmission", name="review_status_date"),
        migrations.RemoveField(model_name="quizsubmission", name="submitted_date"),
        migrations.RemoveField(
            model_name="videointerviewsubmission", name="review_status"
        ),
        migrations.RemoveField(
            model_name="videointerviewsubmission", name="review_status_date"
        ),
        migrations.RemoveField(
            model_name="videointerviewsubmission", name="submitted_date"
        ),
        migrations.AddField(
            model_name="applicationstepsubmission",
            name="review_status",
            field=models.CharField(
                blank=True,
                choices=[("approved", "approved"), ("rejected", "rejected")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applicationstepsubmission",
            name="review_status_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationstepsubmission",
            name="submitted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
