# Generated by Django 2.2.10 on 2020-05-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_bootcampapplication_resume_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcampapplication',
            name='order',
        ),
    ]
