# Generated by Django 2.2.10 on 2020-05-20 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobma", "0003_add_interview_link"),
        ("applications", "0006_change_submission_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videointerviewsubmission", name="video_file"
        ),
        migrations.AddField(
            model_name="videointerviewsubmission",
            name="interview",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobma.Interview",
            ),
            preserve_default=False,
        ),
    ]
