# Generated by Django 2.2.10 on 2020-05-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobma', '0003_add_interview_link'),
        ('applications', '0006_change_submission_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videointerviewsubmission',
            name='video_file',
        ),
        migrations.AddField(
            model_name='videointerviewsubmission',
            name='interview',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videointerviews', to='jobma.Interview'),
            preserve_default=False,
        ),
    ]
