# Generated by Django 2.2.10 on 2020-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_remove_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
