# Generated by Django 2.2.10 on 2020-06-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("applications", "0009_add_step_default_status")]

    operations = [
        migrations.AlterField(
            model_name="applicationstepsubmission",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                    ("waitlisted", "waitlisted"),
                ],
                default="pending",
                max_length=20,
            ),
        )
    ]
