# Generated by Django 2.2.13 on 2020-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("applications", "0010_add_waitlisted_status")]

    operations = [
        migrations.AddField(
            model_name="applicationstepsubmission",
            name="submission_status",
            field=models.CharField(
                choices=[("pending", "pending"), ("submitted", "submitted")],
                default="pending",
                max_length=20,
            ),
        )
    ]
