# Generated by Django 2.2.13 on 2020-06-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("applications", "0012_applicantletter")]

    operations = [
        migrations.RemoveField(model_name="applicantletter", name="is_acceptance"),
        migrations.AddField(
            model_name="applicantletter",
            name="letter_type",
            field=models.CharField(
                choices=[("approved", "approved"), ("rejected", "rejected")],
                default="approved",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
