# Generated by Django 3.2.14 on 2022-11-04 14:12

from django.db import migrations, models
import django.db.models.deletion


def backpopulate_lines(apps, schema_editor):
    """Create a BootcampApplicationLine for each BootcampApplication"""
    BootcampApplication = apps.get_model("applications", "BootcampApplication")
    BootcampApplicationLine = apps.get_model("applications", "BootcampApplicationLine")
    applications = BootcampApplication.objects.iterator()
    for application in applications:
        BootcampApplicationLine.objects.get_or_create(application=application)


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0014_application_refund_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BootcampApplicationLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line",
                        to="applications.bootcampapplication",
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(backpopulate_lines, migrations.RunPython.noop),
    ]
