# Generated by Django 2.2.10 on 2020-05-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobma", "0001_initial"),
        ("klasses", "0015_rename_klass_to_bootcamp_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="klasses.BootcampRun"
            ),
        )
    ]
