# Generated by Django 2.2.10 on 2020-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("jobma", "0002_rename_klass")]

    operations = [
        migrations.RemoveField(model_name="interview", name="interview_id"),
        migrations.AddField(
            model_name="interview",
            name="interview_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
