# Generated by Django 2.2.13 on 2020-06-15 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobma", "0004_interview_results_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="interview", name="candidate_email"),
        migrations.RemoveField(model_name="interview", name="candidate_first_name"),
        migrations.RemoveField(model_name="interview", name="candidate_last_name"),
        migrations.RemoveField(model_name="interview", name="candidate_phone"),
        migrations.AddField(
            model_name="interview",
            name="applicant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
