# Generated by Django 2.2.13 on 2020-06-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobma', '0005_applicant_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klasses.BootcampRun', unique=True),
        ),
    ]
