# Generated by Django 2.2.13 on 2020-06-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("jobma", "0006_one_job_per_run")]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="interview_token",
            field=models.TextField(blank=True, null=True),
        )
    ]
