# Generated by Django 2.2.24 on 2021-08-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobma", "0007_interview_interview_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="klasses.BootcampRun"
            ),
        ),
    ]
