# Generated by Django 3.2.12 on 2022-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobma", "0007_interview_interview_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewaudit",
            name="data_after",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interviewaudit",
            name="data_before",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobaudit",
            name="data_after",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobaudit",
            name="data_before",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
