# Generated by Django 3.2.12 on 2022-04-27 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klasses", "0027_alter_json_fields"),
        ("jobma", "0008_alter_json_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="klasses.bootcamprun"
            ),
        ),
    ]
