version: '2.1'
services:
  db:
    image: postgres:9.6.16
    ports:
      - "5432"

  redis:
    image: redis:3.0.3
    ports:
      - "6379"

  nginx:
    image: nginx:1.9.5
    ports:
      - "8099:8099"
    links:
      - web

  python:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/true
    environment:
      DEBUG: 'False'
      DEV_ENV: 'True'  # necessary to have nginx connect to web container
      NODE_ENV: 'production'
      PORT: 8097
      COVERAGE_DIR: htmlcov
      DATABASE_URL: postgres://postgres@db:5432/postgres
      BOOTCAMP_SECURE_SSL_REDIRECT: 'False'
      BOOTCAMP_DB_DISABLE_SSL: 'True'
      CELERY_TASK_ALWAYS_EAGER: 'False'
      CELERY_BROKER_URL: redis://redis:6379/4
      CELERY_RESULT_BACKEND: redis://redis:6379/4
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      WEBPACK_DEV_SERVER_HOST: ${WEBPACK_DEV_SERVER_HOST:-localhost}
    env_file: .env

  web:
    image: bootcamp_python
    extends:
      service: python
    command: >
      /bin/bash -c '
      sleep 3 &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py migrate --no-input &&
      uwsgi uwsgi.ini'
    ports:
      - "8097:8097"
    links:
      - db
      - redis

  watch:
    build:
      context: .
      dockerfile: Dockerfile-node
    working_dir: /src
    command: >
      /bin/bash -c './webpack_dev_server.sh --install'
    ports:
      - "8098:8098"
    environment:
      NODE_ENV: 'production'
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      CONTAINER_NAME: 'watch'
    env_file: .env

  celery:
    image: bootcamp_python
    extends:
      service: python
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A bootcamp worker -B -l ${BOOTCAMP_LOG_LEVEL:-INFO}'
    links:
      - db
      - redis
