FROM node:6.2
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1

RUN adduser --disabled-password --gecos "" mitodl

RUN npm install -g yarn@0.21.3

RUN mkdir -p /home/mitodl/.cache/yarn

RUN chown mitodl:mitodl /home/mitodl/.cache/yarn

USER mitodl
