db:
  image: postgres
  ports:
    - "5432"

web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python3 manage.py migrate &&
    ./with_host.sh python3 manage.py runserver 0.0.0.0:8099'
  volumes:
    - .:/src
  environment:
    DEBUG: 'True'
    NODE_ENV: 'development'
    PORT: 8099
    COVERAGE_DIR: htmlcov
    DATABASE_URL: postgres://postgres@db:5432/postgres
    BOOTCAMP-ECOMMERCE_USE_WEBPACK_DEV_SERVER: 'True'
    BOOTCAMP-ECOMMERCE_SECURE_SSL_REDIRECT: 'False'
    BOOTCAMP-ECOMMERCE_DB_DISABLE_SSL: 'True'
  env_file: .env
  ports:
    - "8099:8099"
  links:
    - db

watch:
  build: .
  dockerfile: Dockerfile-node
  working_dir: /src
  command: >
    /bin/bash -c './webpack_dev_server.sh --install'
  ports:
    - "8098:8098"
  volumes:
    - .:/src
  environment:
    NODE_ENV: 'development'
  env_file: .env
