# Generated by Django 2.2.10 on 2020-05-06 12:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("cms", "0004_rename_klass_to_bootcamp_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootcamprunpage",
            name="header_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Header image size must be at least 1900x650 pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="bootcamprunpage",
            name="subhead",
            field=models.CharField(
                default="",
                help_text="The subhead to display in the header section on the page.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bootcamprunpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="The description shown on the page."
            ),
        ),
    ]
