# Generated by Django 2.2.10 on 2020-05-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_product_page_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcamprunpage',
            name='content',
        ),
    ]
