# Generated by Django 2.2.10 on 2020-05-11 10:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("cms", "0006_remove_bootcamprunpage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "sections",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "section",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="The heading to display for this section on the page.",
                                                max_length=255,
                                            ),
                                        ),
                                        (
                                            "subhead",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="The subhead to display for this section on the page.",
                                                max_length=255,
                                            ),
                                        ),
                                        (
                                            "members",
                                            wagtail.core.blocks.StreamBlock(
                                                [
                                                    (
                                                        "member",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "name",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="Name of the instructor.",
                                                                        max_length=100,
                                                                    ),
                                                                ),
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        help_text="Profile image size must be at least 300x300 pixels."
                                                                    ),
                                                                ),
                                                                (
                                                                    "title",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="A brief description about the instructor.",
                                                                        max_length=255,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    )
                                                ],
                                                help_text="The instructors to display in this section",
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        help_text="The instructor to display in this section",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
