# Generated by Django 2.2.10 on 2020-05-19 10:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cms", "0008_column_image_text_section")]

    operations = [
        migrations.CreateModel(
            name="SiteNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", wagtail.fields.RichTextField(max_length=255)),
            ],
        )
    ]
