# Generated by Django 2.2.10 on 2020-05-22 11:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("cms", "0010_alumnipage"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorspage",
            name="banner_image",
            field=models.ForeignKey(
                help_text="Image that will display as a banner at the top of the section, must be at least 750x505 pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="instructorspage",
            name="heading",
            field=wagtail.core.fields.RichTextField(
                default="Instructors",
                help_text="The heading to display on this section.",
            ),
        ),
        migrations.AlterField(
            model_name="instructorspage",
            name="sections",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="The heading to display for this section on the page.",
                                        max_length=255,
                                    ),
                                ),
                                (
                                    "subhead",
                                    wagtail.core.blocks.RichTextBlock(
                                        help_text="The subhead to display for this section on the page."
                                    ),
                                ),
                                (
                                    "heading_singular",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Heading that will highlight the instructor point.",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "members",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "member",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "name",
                                                            wagtail.core.blocks.CharBlock(
                                                                help_text="Name of the instructor.",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                help_text="Profile image size must be at least 300x300 pixels."
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.core.blocks.CharBlock(
                                                                help_text="A brief description about the instructor.",
                                                                max_length=255,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        help_text="The instructors to display in this section",
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                help_text="The instructor to display in this section",
            ),
        ),
    ]
