# Generated by Django 2.2.10 on 2020-06-01 09:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        (
            "cms",
            "0011_add_banner_field_and_heading_and_heading_singular_to_instructors_section",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningResourcePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Learning Resources",
                        help_text="The heading to display on this section.",
                        max_length=100,
                    ),
                ),
                (
                    "items",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "item",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="The title to display for this section on the page.",
                                                max_length=100,
                                            ),
                                        ),
                                        (
                                            "links",
                                            wagtail.core.blocks.RichTextBlock(
                                                help_text="Represent resources with the links to display. Add each link in the new line of the editor."
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        help_text="The resources with links to display in this section",
                    ),
                ),
            ],
            options={"verbose_name": "Learning Resources Section"},
            bases=("wagtailcore.page",),
        )
    ]
