# Generated by Django 2.2.10 on 2020-06-02 14:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("cms", "0012_learningresourcepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramDescriptionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "statement",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="The bold statement for the bootcamp program.",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Program Description",
                        help_text="The heading to display in the header section on the page.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        help_text="The body text to display in the header section on the page."
                    ),
                ),
                (
                    "steps",
                    wagtail.fields.StreamField(
                        [
                            (
                                "steps",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Title that will highlight the main point.",
                                                max_length=100,
                                            ),
                                        ),
                                        (
                                            "description",
                                            wagtail.blocks.RichTextBlock(),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        help_text="Enter detail about steps upto max 7 steps.",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload an image that will render in the program description section.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
