# Generated by Django 2.2.10 on 2020-06-05 13:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("cms", "0014_home_page_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="programdescriptionpage",
            name="banner_image",
            field=models.ForeignKey(
                help_text="This image will be rendered in program-description section of home page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AlterField(
            model_name="programdescriptionpage",
            name="statement",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="The bold statement for the bootcamp program in product page.",
            ),
        ),
    ]
