# Generated by Django 2.2.10 on 2020-06-03 09:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("wagtailimages", "0001_squashed_0021"),
        ("cms", "0015_add_banner_image_in_programdescriptionpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionsSectionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        help_text="Any notes to display, e.g. application deadline etc.",
                        max_length=255,
                    ),
                ),
                (
                    "details",
                    wagtail.core.fields.RichTextField(
                        help_text="Admission details that need to be displayed."
                    ),
                ),
                (
                    "bootcamp_format",
                    models.CharField(
                        help_text="Format of the bootcamp, e.g. Online Bootcamp",
                        max_length=255,
                    ),
                ),
                (
                    "bootcamp_format_details",
                    wagtail.core.fields.RichTextField(
                        blank=True, help_text="Details of the format"
                    ),
                ),
                (
                    "dates",
                    models.CharField(
                        help_text="The start/end dates to display for this bootcamp run, e.g. April 17 - June 23, 2020",
                        max_length=255,
                    ),
                ),
                (
                    "dates_details",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        help_text="Any details to show for the bootcamp dates.",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        help_text="The price to display for this bootcamp, e.g. 100"
                    ),
                ),
                (
                    "price_details",
                    wagtail.core.fields.RichTextField(
                        blank=True, help_text="Price details to display if any."
                    ),
                ),
                (
                    "admissions_image",
                    models.ForeignKey(
                        help_text="Image to show at the top of this section, size must be at least 1900x650 pixels.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
