# Generated by Django 2.2.10 on 2020-06-09 10:12

from django.db import migrations
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from wagtail.core.models import Page, Site


HOME_PAGE_SLUG = "home"
DEFAULT_WAGTAIL_HOMEPAGE_PROPS = dict(
    title="Welcome to your new Wagtail site!", depth=2
)
DEFAULT_HOMEPAGE_PROPS = dict(
    title="MIT Bootcamps", tagline="Learn Innovation and Entrepreneurship from MIT"
)
DEFAULT_SITE_PROPS = dict(hostname="localhost", port=80)


def create_home_page(apps, schema_editor):
    """
    Create the home page
    """
    HomePage = apps.get_model("cms", "HomePage")

    root = Page.objects.get(depth=1)
    home_page_content_type = ContentType.objects.get_for_model(HomePage)
    valid_home_page = Page.objects.filter(
        content_type_id=home_page_content_type.id
    ).first()
    if valid_home_page is None:
        valid_home_page = HomePage(
            **DEFAULT_HOMEPAGE_PROPS, content_type_id=home_page_content_type.id
        )
        root.add_child(instance=valid_home_page)
        valid_home_page = (
            Page.objects.filter(content_type_id=home_page_content_type.id)
            .get()
            .specific
        )
    else:
        valid_home_page = valid_home_page.specific
    site, _ = Site.objects.get_or_create(
        is_default_site=True,
        defaults=dict(
            root_page_id=valid_home_page.id,
            site_name=settings.WAGTAIL_SITE_NAME,
            **DEFAULT_SITE_PROPS,
        ),
    )
    if site.root_page_id != valid_home_page.id:
        site.root_page_id = valid_home_page.id
        site.save()
    wagtail_default_home_page = Page.objects.filter(
        depth=2, content_type=ContentType.objects.get_for_model(Page)
    ).first()
    if wagtail_default_home_page is not None:
        descendants = wagtail_default_home_page.get_children()
        for descendant in descendants:
            Page.objects.get(id=descendant.id).move(valid_home_page, "last-child")
        # Only unpublishing here because if we have other models that haven't run their migrations yet
        # TreeBeard also tries to delete those and results in an exception.
        wagtail_default_home_page.unpublish()
    valid_home_page.save_revision().publish()


def remove_home_page(apps, schema_editor):
    """
    Remove the home page
    """
    HomePage = apps.get_model("cms", "HomePage")

    home_page = Page.objects.filter(
        content_type=ContentType.objects.get_for_model(HomePage)
    ).first()
    default_wagtail_home_page = Page.objects.filter(
        **DEFAULT_WAGTAIL_HOMEPAGE_PROPS
    ).first()
    if not default_wagtail_home_page:
        default_wagtail_home_page = Page(**DEFAULT_WAGTAIL_HOMEPAGE_PROPS)
        root = Page.objects.get(depth=1)
        root.add_child(instance=default_wagtail_home_page)

    if home_page:
        descendants = home_page.get_children()
        for descendant in descendants:
            Page.objects.get(id=descendant.id).move(
                default_wagtail_home_page, "last-child"
            )
        # Only unpublishing here because if we have other models that haven't run their migrations yet
        # TreeBeard also tries to delete those and results in an exception.
        home_page.specific.unpublish()
    site = Site.objects.filter(is_default_site=True).first()
    if site:
        site.root_page = default_wagtail_home_page
        site.save()
    default_wagtail_home_page.save_revision().publish()


class Migration(migrations.Migration):

    dependencies = [("cms", "0018_bootcamp_index_page")]

    operations = [migrations.RunPython(create_home_page, remove_home_page)]
