# Generated by Django 2.2.10 on 2020-06-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cms", "0018_bootcamp_index_page")]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)
    ]
