# Generated by Django 2.2.13 on 2020-06-16 09:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("cms", "0019_create_and_setup_home_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogGridPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "contents",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "bootcamp_run",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                "cms.BootcampRunPage",
                                                help_text="The bootcamp run to display",
                                            ),
                                        ),
                                        (
                                            "format",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="The bootcamp format to display, e.g. Online Bootcamp",
                                                max_length=128,
                                            ),
                                        ),
                                        (
                                            "application_deadline",
                                            wagtail.core.blocks.DateTimeBlock(
                                                help_text="The application deadline to display for this bootcamp run"
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        help_text="The bootcamps to display in this catalog section",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
