# Generated by Django 2.2.13 on 2020-06-22 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0004_add_verbose_name_plural"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailimages", "0001_squashed_0021"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("cms", "0020_home_catalog_section"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdmissionsSectionPage", new_name="AdmissionsSection"
        ),
        migrations.RenameModel(old_name="AlumniPage", new_name="AlumniSection"),
        migrations.RenameModel(
            old_name="CatalogGridPage", new_name="CatalogGridSection"
        ),
        migrations.RenameModel(old_name="HomeAlumniPage", new_name="HomeAlumniSection"),
        migrations.RenameModel(
            old_name="InstructorsPage", new_name="InstructorsSection"
        ),
        migrations.RenameModel(
            old_name="LearningResourcePage", new_name="LearningResourceSection"
        ),
        migrations.RenameModel(
            old_name="ProgramDescriptionPage", new_name="ProgramDescriptionSection"
        ),
        migrations.RenameModel(
            old_name="ThreeColumnImageTextPage", new_name="ThreeColumnImageTextSection"
        ),
    ]
