# Generated by Django 2.2.13 on 2020-06-24 16:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("cms", "0022_model_rename_page_to_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterTemplatePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "acceptance_text",
                    wagtail.core.fields.RichTextField(
                        default="Dear {{ first_name }},<br />\n<br />\nOn behalf of the MIT Bootcamps Admissions Committee, I am delighted to inform you of your admission to the {{ bootcamp_name }} on {{ bootcamp_start_date }}. The cost of tuition for this Bootcamp is {{ price }}<br />\n<br />\nYou were selected from an outstanding pool of applicants based on the selection criteria: capacity for calculated risk, open and critical thinking, initiative with follow-through, and focus on community. MIT’s mission is to educate students in science and technology to best prepare them to solve the world’s greatest challenges.<br />\n<br />\nYou are invited to be a part of this mission.<br />\n<br />\nIf you choose to attend the {{ bootcamp_name }}, MIT is dedicated to providing you with an education that combines rigorous academic study with the excitement of discovery, support and intellectual stimulation in an intense, immersive experience. You will be pushed to your limits, inspired, challenged and supported by your peers, faculty, students, mentors and alumni from around the world.<br />\n<br />\nIt will be a life-changing experience.<br />\n<br />\nCongratulations on your admission! I look forward to hearing from you and hope you can join us at the Bootcamp.<br />\n"
                    ),
                ),
                (
                    "rejection_text",
                    wagtail.core.fields.RichTextField(
                        default="Dear {{ first_name }},<br />\n<br />\nAfter careful consideration, we regret to inform you that we are unable to proceed further in the admissions process for the {{ bootcamp_name }}. Based on our review, we believe you have the potential but are not ready at this time for the Bootcamp.<br />\n<br />\nWe hope you will take this as an opportunity to improve and re-apply at the next opportunity. Please read on to learn more about our process.<br />\n<br />\nIt was a tough decision. We select applicants who have a demonstrated capacity for calculated risk, open and critical thinking, initiative with follow through, and focus on community. Specifically, we offer admission to applicants that complement one another’s skillsets for this Bootcamp.<br />\n<br />\nWe found your story inspiring and liked the problems you’re trying to solve. We hope that you will continue working on it because the world needs entrepreneurs like you.<br />\n<br />\nThis is NOT a good-bye but rather a see you later.<br />\n"
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        )
    ]
