# Generated by Django 2.2.13 on 2020-06-25 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cms", "0022_model_rename_page_to_section")]

    operations = [
        migrations.AlterField(
            model_name="resourcepage",
            name="header_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Upload a header image that will render in the resource page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        )
    ]
