# Generated by Django 2.2.13 on 2020-08-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("cms", "0025_add_resource_pages_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="lettertemplatepage",
            name="signatory_name",
            field=models.CharField(
                default="", help_text="Name of the signatory.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="lettertemplatepage",
            name="signature_image",
            field=models.ForeignKey(
                help_text="Upload an image that will render in the program description section.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
