# Generated by Django 2.2.13 on 2020-10-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cms", "0027_letter_template_image_blank")]

    operations = [
        migrations.AlterField(
            model_name="bootcamprunpage",
            name="bootcamp_run",
            field=models.OneToOneField(
                blank=True,
                help_text="The bootcamp run for this page",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="klasses.BootcampRun",
            ),
        )
    ]
