# Generated by Django 2.2.13 on 2020-12-17 12:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("cms", "0028_allow_blank_bootcamprun_in_bootcamprunpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificatePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "sub_title",
                    models.CharField(
                        help_text="Specify the bootcamp certificate sub title.",
                        max_length=250,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Optional text field for bootcamp location.",
                        max_length=250,
                    ),
                ),
                (
                    "signatories",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "signatory",
                                wagtail.core.blocks.PageChooserBlock(
                                    page_type=["cms.SignatoryPage"], required=True
                                ),
                            )
                        ],
                        help_text="You can choose upto 5 signatories.",
                    ),
                ),
            ],
            options={"verbose_name": "Certificate"},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SignatoryIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                )
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SignatoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the signatory.", max_length=250
                    ),
                ),
                (
                    "title_1",
                    models.CharField(
                        blank=True,
                        help_text="Specify signatory first title in organization.",
                        max_length=250,
                    ),
                ),
                (
                    "title_2",
                    models.CharField(
                        blank=True,
                        help_text="Specify signatory second title in organization.",
                        max_length=250,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Specify the organization of signatory.",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "signature_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Signature image size must be at least 150x50 pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={"verbose_name": "Signatory"},
            bases=("wagtailcore.page",),
        ),
    ]
