# Generated by Django 2.2.13 on 2020-12-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("cms", "0030_add_certificateindexpage_for_certificate_routing"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatepage",
            name="granting_institution",
            field=models.CharField(
                default="Massachusetts Institute of Technology",
                help_text="Specify the granting institution name. e.g. MIT Bootcamps & Harvard Medical School Center for Primary Care.",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="certificatepage",
            name="secondary_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Representing the institution image, This image will be rendered over the certificate as secondary image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
