# Generated by Django 2.2.13 on 2021-01-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cms", "0031_certificatepage_new_fields")]

    operations = [
        migrations.AlterField(
            model_name="signatorypage",
            name="signature_image",
            field=models.ForeignKey(
                help_text="Signature image size must be at least 150x50 pixels.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.Image",
            ),
        )
    ]
