# Generated by Django 2.2.18 on 2021-06-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0032_make_certificate_signatory_images_mandatory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signatorypage",
            name="signature_image",
            field=models.ForeignKey(
                help_text="Signature image size must be at least 150x50 pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
