# Generated by Django 3.2.12 on 2022-04-27 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("cms", "0033_apply_admission_text_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signatorypage",
            name="signature_image",
            field=models.ForeignKey(
                help_text="Signature image size must be at least 150x50 pixels.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
