# Generated by Django 3.2.14 on 2022-11-10 01:01

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0034_signatory_image_set_null_on_delete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionssection",
            name="bootcamp_format",
        ),
        migrations.RemoveField(
            model_name="admissionssection",
            name="bootcamp_format_details",
        ),
        migrations.AddField(
            model_name="admissionssection",
            name="bootcamp_location",
            field=models.CharField(
                default="Online",
                help_text="Location of the bootcamp, e.g. Online Bootcamp",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admissionssection",
            name="bootcamp_location_details",
            field=wagtail.core.fields.RichTextField(
                blank=True, help_text="Details of the location", null=True
            ),
        ),
    ]
