# Generated by Django 3.2.16 on 2023-10-27 11:32

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("wagtailcore", "0066_collection_management_permissions"),
        ("cms", "0035_rename_admissions_format_to_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorssection",
            name="sections",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="The heading to display for this section on the page.",
                                        max_length=255,
                                    ),
                                ),
                                (
                                    "subhead",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="The subhead to display for this section on the page."
                                    ),
                                ),
                                (
                                    "heading_singular",
                                    wagtail.blocks.CharBlock(
                                        help_text="Heading that will highlight the instructor or sponsor point.",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "members",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "member",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "name",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Name of the instructor/sponsor.",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                help_text="Profile image size must be at least 300x300 pixels."
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="A brief description about the instructor/sponsor.",
                                                                max_length=255,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        help_text="The instructors to display in this section",
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                help_text="The instructor to display in this section",
            ),
        ),
        migrations.CreateModel(
            name="SponsorsSection",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "heading",
                    wagtail.fields.RichTextField(
                        default="Sponsors",
                        help_text="The heading to display on this section.",
                    ),
                ),
                (
                    "sections",
                    wagtail.fields.StreamField(
                        [
                            (
                                "section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="The heading to display for this section on the page.",
                                                max_length=255,
                                            ),
                                        ),
                                        (
                                            "subhead",
                                            wagtail.blocks.RichTextBlock(
                                                help_text="The subhead to display for this section on the page."
                                            ),
                                        ),
                                        (
                                            "heading_singular",
                                            wagtail.blocks.CharBlock(
                                                help_text="Heading that will highlight the instructor or sponsor point.",
                                                max_length=100,
                                            ),
                                        ),
                                        (
                                            "sponsors",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "sponsor",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "name",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="Name of the instructor/sponsor.",
                                                                        max_length=100,
                                                                    ),
                                                                ),
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        help_text="Profile image size must be at least 300x300 pixels."
                                                                    ),
                                                                ),
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="A brief description about the instructor/sponsor.",
                                                                        max_length=255,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    )
                                                ],
                                                help_text="The sponsors to display in this section",
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        help_text="The sponsor to display in this section",
                    ),
                ),
                (
                    "banner_image",
                    models.ForeignKey(
                        help_text="Image that will display as a banner at the top of the section, must be at least 750x505 pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
