# Generated by Django 3.2.23 on 2023-11-28 13:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0036_add_sponsors_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumnisection",
            name="alumni_bios",
            field=wagtail.fields.StreamField(
                [
                    (
                        "alumni",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="The image of the alumni"
                                    ),
                                ),
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Name of the alumni.", max_length=100
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="The title to display after the name.",
                                        max_length=255,
                                    ),
                                ),
                                (
                                    "class_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="A brief description about the alumni class.",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "quote",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="The quote that appears on the alumni section."
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                help_text="Alumni to display in this section.",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="cataloggridsection",
            name="contents",
            field=wagtail.fields.StreamField(
                [
                    (
                        "bootcamp_run",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(
                                        "cms.BootcampRunPage",
                                        help_text="The bootcamp run to display",
                                    ),
                                ),
                                (
                                    "format",
                                    wagtail.blocks.CharBlock(
                                        help_text="The bootcamp format to display, e.g. Online Bootcamp",
                                        max_length=128,
                                    ),
                                ),
                                (
                                    "application_deadline",
                                    wagtail.blocks.DateTimeBlock(
                                        help_text="The application deadline to display for this bootcamp run"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="The bootcamps to display in this catalog section",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="certificatepage",
            name="signatories",
            field=wagtail.fields.StreamField(
                [
                    (
                        "signatory",
                        wagtail.blocks.PageChooserBlock(
                            page_type=["cms.SignatoryPage"], required=True
                        ),
                    )
                ],
                help_text="You can choose upto 5 signatories.",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="instructorssection",
            name="sections",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="The heading to display for this section on the page.",
                                        max_length=255,
                                    ),
                                ),
                                (
                                    "subhead",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="The subhead to display for this section on the page."
                                    ),
                                ),
                                (
                                    "heading_singular",
                                    wagtail.blocks.CharBlock(
                                        help_text="Heading that will highlight the instructor or sponsor point.",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "members",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "member",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "name",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Name of the instructor/sponsor.",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                help_text="Profile image size must be at least 300x300 pixels."
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="A brief description about the instructor/sponsor.",
                                                                max_length=255,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        help_text="The instructors to display in this section",
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                help_text="The instructor to display in this section",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="learningresourcesection",
            name="items",
            field=wagtail.fields.StreamField(
                [
                    (
                        "item",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="The title to display for this section on the page.",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Represent resources with the links to display. Add each link in the new line of the editor."
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                help_text="The resources with links to display in this section",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="programdescriptionsection",
            name="steps",
            field=wagtail.fields.StreamField(
                [
                    (
                        "steps",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title that will highlight the main point.",
                                        max_length=100,
                                    ),
                                ),
                                ("description", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                help_text="Enter detail about steps upto max 7 steps.",
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="resourcepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(max_length=100)),
                                ("detail", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                help_text="Enter details of content.",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorssection",
            name="sections",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="The heading to display for this section on the page.",
                                        max_length=255,
                                    ),
                                ),
                                (
                                    "subhead",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="The subhead to display for this section on the page."
                                    ),
                                ),
                                (
                                    "heading_singular",
                                    wagtail.blocks.CharBlock(
                                        help_text="Heading that will highlight the instructor or sponsor point.",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "sponsors",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "sponsor",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "name",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Name of the instructor/sponsor.",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                help_text="Profile image size must be at least 300x300 pixels."
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="A brief description about the instructor/sponsor.",
                                                                max_length=255,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        help_text="The sponsors to display in this section",
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                help_text="The sponsor to display in this section",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="threecolumnimagetextsection",
            name="column_image_text_section",
            field=wagtail.fields.StreamField(
                [
                    (
                        "column_image_text_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="Heading that will highlight the main point.",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "sub_heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="Area sub heading.", max_length=250
                                    ),
                                ),
                                ("body", wagtail.blocks.RichTextBlock()),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="image size must be at least 150x50 pixels."
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                help_text="Enter detail about area upto max 3 blocks.",
                null=True,
                use_json_field=True,
            ),
        ),
    ]
