# Generated by Django 3.2.14 on 2022-11-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0034_signatory_image_set_null_on_delete"),
    ]

    operations = [
        migrations.RenameField(
            "admissionssection",
            "bootcamp_format",
            "bootcamp_location",
        ),
        migrations.RenameField(
            "admissionssection",
            "bootcamp_format_details",
            "bootcamp_location_details",
        ),
    ]
