# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deadline', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klasses.Bootcamp')),
            ],
        ),
        migrations.AddField(
            model_name='installment',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klasses.Klass'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together=set([('klass', 'installment_number')]),
        ),
    ]
