# Generated by Django 1.10.5 on 2017-05-16 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("klasses", "0006_removed_installment_number")]

    operations = [
        migrations.AlterUniqueTogether(
            name="installment",
            unique_together=set([("klass", "deadline")]),  # noqa: C405
        ),
        migrations.AlterIndexTogether(
            name="installment",
            index_together=set([("klass", "deadline")]),  # noqa: C405
        ),
    ]
