# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("klasses", "0007_add_installment_index")]

    operations = [
        migrations.AlterUniqueTogether(
            name="bootcampadmissioncache", unique_together=set([])
        ),
        migrations.RemoveField(model_name="bootcampadmissioncache", name="klass"),
        migrations.RemoveField(model_name="bootcampadmissioncache", name="user"),
        migrations.DeleteModel(name="BootcampAdmissionCache"),
    ]
