# Generated by Django 2.2.9 on 2020-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("klasses", "0013_personalprice_application_stage")]

    operations = [
        migrations.AlterField(
            model_name="personalprice",
            name="application_stage",
            field=models.TextField(blank=True),
        )
    ]
