# Generated by Django 2.2.13 on 2020-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("klasses", "0017_nullable_source")]

    operations = [
        migrations.AddField(
            model_name="bootcamprunenrollment",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether or not this enrollment should be considered active",
            ),
        ),
        migrations.AddField(
            model_name="bootcamprunenrollment",
            name="change_status",
            field=models.CharField(
                blank=True, choices=[("refunded", "refunded")], max_length=20, null=True
            ),
        ),
    ]
