# Generated by Django 2.2.13 on 2020-08-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("klasses", "0018_bootcamp_enrollment_status_fields")]

    operations = [
        migrations.AlterField(
            model_name="bootcamprun",
            name="run_key",
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterUniqueTogether(name="bootcamprun", unique_together=set()),
    ]
