# Generated by Django 2.2.13 on 2020-09-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("klasses", "0019_bootcamprun_update_run_key_indexes")]

    operations = [
        migrations.AddField(
            model_name="bootcamprun",
            name="novoed_course_stub",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bootcamprunenrollment",
            name="novoed_sync_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
