# Generated by Django 2.2.13 on 2020-12-16 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("klasses", "0020_add_novoed"),
    ]

    operations = [
        migrations.CreateModel(
            name="BootcampRunCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "is_revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether or not the certificate is revoked",
                        verbose_name="revoked",
                    ),
                ),
                (
                    "bootcamp_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klasses.BootcampRun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("user", "bootcamp_run")}},
        )
    ]
