# Generated by Django 2.2.13 on 2020-12-23 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("klasses", "0021_bootcampruncertificate")]

    operations = [
        migrations.AlterField(
            model_name="bootcampruncertificate",
            name="bootcamp_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="klasses.BootcampRun",
            ),
        )
    ]
