# Generated by Django 2.2.13 on 2021-01-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("klasses", "0022_add_related_name_in_bootcampruncertificate")]

    operations = [
        migrations.AddField(
            model_name="bootcamprunenrollment",
            name="user_certificate_is_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether or not this user enrollment will get certificate.",
            ),
        )
    ]
