# Generated by Django 2.2.18 on 2021-03-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klasses", "0023_bootcamprunenrollment_user_certificate_is_blocked")
    ]

    operations = [
        migrations.AddField(
            model_name="bootcamprun",
            name="bootcamp_run_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        )
    ]
