# Generated by Django 2.2.13 on 2021-03-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("klasses", "0024_add_bootcamp_run_id")]

    operations = [
        migrations.AddField(
            model_name="bootcamprun",
            name="allows_skipped_steps",
            field=models.BooleanField(default=False),
        )
    ]
