# Generated by Django 3.2.12 on 2022-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klasses", "0026_add_bootcamprunenrollmentaudit_defer_enrollment_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bootcamprunenrollmentaudit",
            name="data_after",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bootcamprunenrollmentaudit",
            name="data_before",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
