# Generated by Django 3.2.23 on 2023-11-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klasses", "0027_alter_json_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootcamprun",
            name="early_bird_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
