# Generated by Django 3.2.25 on 2024-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("klasses", "0028_add_early_bird_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="bootcamp",
            name="readable_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                help_text="The unique string to identify this bootcamp. It can be of the form "
                "'bootcamp-v1:TYPE+TOPIC-FORMAT' (example: bootcamp-v1:public+IE-f2f)",
            ),
        ),
    ]
