# Generated by Django 3.2.25 on 2024-04-05 17:05

from django.db import migrations


def backpopulate_readable_id(apps, schema_editor):
    """Backpopulate readble_id for existing bootcamps"""
    BootcampRun = apps.get_model("klasses", "BootcampRun")
    Bootcamp = apps.get_model("klasses", "Bootcamp")
    for bootcamp in Bootcamp.objects.filter(readable_id=None).iterator():
        bootcamp_run_id = (
            BootcampRun.objects.filter(
                bootcamp_run_id__isnull=False, bootcamp_id=bootcamp.id
            )
            .first()
            .bootcamp_run_id
        )
        run = bootcamp_run_id.split("+")[-1]
        bootcamp.readable_id = bootcamp_run_id.removesuffix(f"+{run}")
        bootcamp.save()


class Migration(migrations.Migration):

    dependencies = [
        ("klasses", "0029_bootcamp_readable_id"),
    ]

    operations = [
        migrations.RunPython(backpopulate_readable_id, migrations.RunPython.noop),
    ]
