# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-13 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("klasses", "0013_personalprice_application_stage"),
        ("hubspot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubspotLineResync",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personal_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klasses.PersonalPrice",
                    ),
                ),
            ],
        )
    ]
