# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ecommerce", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="line", name="klasse_id"),
        migrations.AddField(
            model_name="line",
            name="klass_id",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
