# Generated by Django 2.2.13 on 2020-07-15 14:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_application_refund_status"),
        ("ecommerce", "0004_rename_klass_to_bootcamp_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="applications.BootcampApplication",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("cybersource", "cybersource"),
                    ("wiretransfer", "wiretransfer"),
                    ("refund", "refund"),
                ],
                default="cybersource",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="WireTransferReceipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("wire_transfer_id", models.IntegerField()),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.Order",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
