# Generated by Django 2.2.13 on 2020-08-10 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klasses", "0018_bootcamp_enrollment_status_fields"),
        ("ecommerce", "0005_application_multiple_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="bootcamp_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="klasses.BootcampRun",
            ),
        )
    ]
