# Generated by Django 2.2.13 on 2020-08-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("ecommerce", "0007_data_migration_for_ecommerce_bootcamp_run_id")]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="bootcamp_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="klasses.BootcampRun"
            ),
        ),
        migrations.AlterField(
            model_name="line", name="run_key", field=models.IntegerField(null=True)
        ),
    ]
