# Generated by Django 2.2.13 on 2020-08-20 17:41

from django.db import migrations


def generate_bootcamp_run_key(apps, schema_editor):
    Line = apps.get_model("ecommerce", "Line")
    BootcampRun = apps.get_model("klasses", "BootcampRun")

    for line in Line.objects.all():
        run = BootcampRun.objects.filter(id=line.bootcamp_run_id).first()
        line.run_key = run.run_key
        line.save()


class Migration(migrations.Migration):
    dependencies = [("ecommerce", "0008_make_line_bootcamp_run_id_non_nullable")]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, reverse_code=generate_bootcamp_run_key
        ),
        migrations.RemoveField(model_name="line", name="run_key"),
    ]
