# Generated by Django 2.2.13 on 2020-07-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("ecommerce", "0009_remove_line_run_key")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("cybersource", "cybersource"),
                    ("wiretransfer", "wiretransfer"),
                    ("refund", "refund"),
                ],
                default="cybersource",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="WireTransferReceipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("wire_transfer_id", models.IntegerField()),
                ("data", models.JSONField()),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.Order",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
