# Generated by Django 3.2.12 on 2022-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0010_wire_transfers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaudit",
            name="data_after",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderaudit",
            name="data_before",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="wiretransferreceipt",
            name="data",
            field=models.JSONField(),
        ),
    ]
