"""Compliance constants"""

# computed result states
RESULT_SUCCESS = "SUCCESS"
RESULT_MANUALLY_APPROVED = "MANUALLY_APPROVED"
RESULT_DENIED = "DENIED"
RESULT_TEMPORARY_FAILURE = "TEMPORARY_FAILURE"
RESULT_UNKNOWN = "UNKNOWN"
RESULT_CHOICES = (
    RESULT_SUCCESS,
    RESULT_MANUALLY_APPROVED,
    RESULT_DENIED,
    RESULT_TEMPORARY_FAILURE,
    RESULT_UNKNOWN,
)

# REASON CODES

# "SUCCESS"
REASON_CODE_SUCCESS = 100

# INPUT ERRORS
REASON_CODE_MISSING_FIELDS = 101
REASON_CODE_INVALID_FIELDS = 102

# ADDRESS VALIDATION ERRORS
# These error codes are not returned from compliance api, We use them to identify
# the fields that failed validation
REASON_CODE_INVALID_FIELD_FIRST_NAME = 301
REASON_CODE_INVALID_FIELD_LAST_NAME = 302
REASON_CODE_INVALID_FIELD_STREET = 303
REASON_CODE_INVALID_FIELD_CITY = 304
REASON_CODE_INVALID_FIELD_COUNTRY = 305
REASON_CODE_INVALID_FIELD_STATE = 306
REASON_CODE_INVALID_FIELD_POSTAL_CODE = 307


class ComplianceAddressPayload:
    """Class to hold keys for export compliance API payload"""

    CS_KEY_FIRST_NAME = "firstName"
    CS_KEY_LAST_NAME = "lastName"
    CS_KEY_EMAIL = "email"
    CS_KEY_STREET1 = "street1"
    CS_KEY_STREET2 = "street2"
    CS_KEY_STREET3 = "street3"
    CS_KEY_STREET4 = "street4"
    CS_KEY_CITY = "city"
    CS_KEY_COUNTRY = "country"
    CS_KEY_STATE = "state"
    CS_KEY_POSTAL_CODE = "postalCode"

    ADDRESS_PAYLOAD_ERROR_CODES = {
        CS_KEY_FIRST_NAME: REASON_CODE_INVALID_FIELD_FIRST_NAME,
        CS_KEY_LAST_NAME: REASON_CODE_INVALID_FIELD_LAST_NAME,
        (
            CS_KEY_STREET1,
            CS_KEY_STREET2,
            CS_KEY_STREET3,
            CS_KEY_STREET4,
        ): REASON_CODE_INVALID_FIELD_STREET,
        CS_KEY_CITY: REASON_CODE_INVALID_FIELD_CITY,
        CS_KEY_COUNTRY: REASON_CODE_INVALID_FIELD_COUNTRY,
        CS_KEY_STATE: REASON_CODE_INVALID_FIELD_STATE,
        CS_KEY_POSTAL_CODE: REASON_CODE_INVALID_FIELD_POSTAL_CODE,
    }


# BACKEND FAILURES
REASON_CODE_GENERAL_FAILURE = 150
REASON_CODE_SERVER_TIMEOUT = 151
REASON_CODE_SERVICE_TIMEOUT = 152

REASON_CODES_RETRYABLE = [
    REASON_CODE_GENERAL_FAILURE,
    REASON_CODE_MISSING_FIELDS,
    REASON_CODE_INVALID_FIELDS,
    REASON_CODE_SERVER_TIMEOUT,
    REASON_CODE_SERVICE_TIMEOUT,
]

# CONFIGURATION FAILURES
REASON_CODE_MERCHANT_CONFIG_ERROR = 234

# EXPORTS DENIED
REASON_CODE_EMBARGO_CUSTOMER = 700
REASON_CODE_EMBARGO_COUNTRY = 701
REASON_CODE_EMBARGO_COUNTRY_EMAIL = 702
REASON_CODE_EMBARGO_COUNTRY_BY_IP = 703

# REASON CODE SETS
INVALID_REQUEST_REASON_CODES = [REASON_CODE_MISSING_FIELDS, REASON_CODE_INVALID_FIELDS]
CYBERSOURCE_BACKEND_FAILURE_REASON_CODES = [
    REASON_CODE_GENERAL_FAILURE,
    REASON_CODE_SERVER_TIMEOUT,
    REASON_CODE_SERVICE_TIMEOUT,
]
CYBERSOURCE_CONFIG_ERROR_REASON_CODES = [REASON_CODE_MERCHANT_CONFIG_ERROR]

TEMPORARY_FAILURE_REASON_CODES = (
    INVALID_REQUEST_REASON_CODES
    + CYBERSOURCE_BACKEND_FAILURE_REASON_CODES
    + CYBERSOURCE_CONFIG_ERROR_REASON_CODES
)

EXPORTS_BLOCKED_REASON_CODES = [
    REASON_CODE_EMBARGO_CUSTOMER,
    REASON_CODE_EMBARGO_COUNTRY,
    REASON_CODE_EMBARGO_COUNTRY_EMAIL,
    REASON_CODE_EMBARGO_COUNTRY_BY_IP,
]
