FROM mitodl/bootcamp_watch_travis_next

WORKDIR /src

COPY package.json /src

COPY yarn.lock /src

ADD ./webpack_if_prod.sh /src

USER mitodl

RUN yarn install --frozen-lockfile

COPY . /src

USER root

RUN chown -R mitodl:mitodl /src

USER mitodl
