FROM mitodl/bootcamp_watch_travis_4db5a4

WORKDIR /src

COPY package.json yarn.lock webpack_if_prod.sh /src/

USER root

COPY . /src

RUN chown -R node:node /src

USER node

RUN yarn install --frozen-lockfile --ignore-engines
