# Generated by Django 1.10.5 on 2017-10-06 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("mail", "0002_default_email_templates")]

    operations = [
        migrations.RemoveField(
            model_name="sentautomaticemails", name="automatic_email"
        ),
        migrations.RemoveField(model_name="sentautomaticemails", name="klass"),
        migrations.RemoveField(model_name="sentautomaticemails", name="user"),
        migrations.DeleteModel(name="AutomaticReminderEmail"),
        migrations.DeleteModel(name="SentAutomaticEmails"),
    ]
