"""constants for Jobma"""

PENDING = "pending"
COMPLETED = "completed"
REJECTED = "rejected"
EXPIRED = "expired"
JOBMA_INTERVIEW_STATUSES = [PENDING, COMPLETED, REJECTED, EXPIRED]
JOBMA_COMPLETED_INTERVIEW_STATUSES = [COMPLETED, REJECTED, EXPIRED]
